### ISSUE TITLE
Fix 500 error on Production

### ISSUE THREAD

**Issue by LewisCrabtree** [LewisCrabtree/DynastyTools#10]
See: https://www.consensusrankings.com/

**Comment by LewisCrabtree** [comment]
2021-08-05T03:54:33.142234+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=www.consensusrankings.com request_id=93cb4298-631a-4730-af73-b390ae66d880 fwd="70.68.224.255" dyno=web.1 connect=5ms service=638ms status=404 bytes=2713 protocol=http
2021-08-05T03:54:33.142462+00:00 app[web.1]: 10.7.237.91 - - [05/Aug/2021:03:54:33 +0000] "GET /favicon.ico HTTP/1.1" 404 2459 "http://www.consensusrankings.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
2021-08-05T03:54:33.171239+00:00 app[web.1]: Internal Server Error: /api/players/
2021-08-05T03:54:33.171241+00:00 app[web.1]: Traceback (most recent call last):
2021-08-05T03:54:33.171242+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-08-05T03:54:33.171244+00:00 app[web.1]: return self.cursor.execute(sql, params)
2021-08-05T03:54:33.171245+00:00 app[web.1]: psycopg2.errors.UndefinedColumn: column rankingsApp_player.Age does not exist
2021-08-05T03:54:33.171246+00:00 app[web.1]: LINE 1: ..."."Deviation", "rankingsApp_player"."Volatility", "rankingsA...
2021-08-05T03:54:33.171246+00:00 app[web.1]: ^
2021-08-05T03:54:33.171247+00:00 app[web.1]:
2021-08-05T03:54:33.171247+00:00 app[web.1]:
2021-08-05T03:54:33.171247+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2021-08-05T03:54:33.171248+00:00 app[web.1]:
2021-08-05T03:54:33.171248+00:00 app[web.1]: Traceback (most recent call last):
2021-08-05T03:54:33.171249+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
2021-08-05T03:54:33.171249+00:00 app[web.1]: response = get_response(request)
2021-08-05T03:54:33.171249+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
2021-08-05T03:54:33.171250+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2021-08-05T03:54:33.171252+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2021-08-05T03:54:33.171253+00:00 app[web.1]: return view_func(*args, **kwargs)
2021-08-05T03:54:33.171253+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
2021-08-05T03:54:33.171253+00:00 app[web.1]: return self.dispatch(request, *args, **kwargs)
2021-08-05T03:54:33.171254+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
2021-08-05T03:54:33.171254+00:00 app[web.1]: response = self.handle_exception(exc)
2021-08-05T03:54:33.171254+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
2021-08-05T03:54:33.171255+00:00 app[web.1]: self.raise_uncaught_exception(exc)
2021-08-05T03:54:33.171255+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2021-08-05T03:54:33.171255+00:00 app[web.1]: raise exc
2021-08-05T03:54:33.171256+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
2021-08-05T03:54:33.171256+00:00 app[web.1]: response = handler(request, *args, **kwargs)
2021-08-05T03:54:33.171257+00:00 app[web.1]: File "/app/rankingsApp/api/views.py", line 28, in get
2021-08-05T03:54:33.171257+00:00 app[web.1]: return Response(serializer.data)
2021-08-05T03:54:33.171258+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 745, in data
2021-08-05T03:54:33.171258+00:00 app[web.1]: ret = super().data
2021-08-05T03:54:33.171258+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 246, in data
2021-08-05T03:54:33.171259+00:00 app[web.1]: self._data = self.to_representation(self.instance)
2021-08-05T03:54:33.171259+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 664, in to_representation
2021-08-05T03:54:33.171260+00:00 app[web.1]: self.child.to_representation(item) for item in iterable
2021-08-05T03:54:33.171260+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 287, in __iter__
2021-08-05T03:54:33.171260+00:00 app[web.1]: self._fetch_all()
2021-08-05T03:54:33.171261+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
2021-08-05T03:54:33.171261+00:00 app[web.1]: self._result_cache = list(self._iterable_class(self))
2021-08-05T03:54:33.171262+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
2021-08-05T03:54:33.171262+00:00 app[web.1]: results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
2021-08-05T03:54:33.171262+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
2021-08-05T03:54:33.171263+00:00 app[web.1]: cursor.execute(sql, params)
2021-08-05T03:54:33.171263+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
2021-08-05T03:54:33.171264+00:00 app[web.1]: return super().execute(sql, params)
2021-08-05T03:54:33.171264+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
2021-08-05T03:54:33.171264+00:00 app[web.1]: return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-08-05T03:54:33.171265+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-08-05T03:54:33.171265+00:00 app[web.1]: return executor(sql, params, many, context)
2021-08-05T03:54:33.171266+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-08-05T03:54:33.171266+00:00 app[web.1]: return self.cursor.execute(sql, params)
2021-08-05T03:54:33.171267+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
2021-08-05T03:54:33.171267+00:00 app[web.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
2021-08-05T03:54:33.171267+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-08-05T03:54:33.171268+00:00 app[web.1]: return self.cursor.execute(sql, params)
2021-08-05T03:54:33.171268+00:00 app[web.1]: django.db.utils.ProgrammingError: column rankingsApp_player.Age does not exist
2021-08-05T03:54:33.171277+00:00 app[web.1]: LINE 1: ..."."Deviation", "rankingsApp_player"."Volatility", "rankingsA...
2021-08-05T03:54:33.171277+00:00 app[web.1]: ^
2021-08-05T03:54:33.171278+00:00 app[web.1]:
